server:
  port: 8086
spring:
  application:
    name: shipping-service
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
app:
  rabbitmq:
    exchange: urbancart.exchange
    order-confirmed-routing-key: order.confirmed
    payment-completed-routing-key: payment.completed
    shipment-created-routing-key: shipment.created
